n1=10
n2=3
add=n1+n2
sub=n1-n2
div=n1/n2
mul=n1*n2
flr=n1//n2
mod=n1%n2
print("addition:",add)
print("subsraction:",sub)
print("division:",div)
print("Multiplication:",mul)
print("mod:",mod)
print("floor:",flr)